spring:
  application:
    name: jah-bot
  ai:
    openai:
      api-key: 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